server:
  port: 8761 #启动端口

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}         #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false   #Eureka服务端关闭心跳连接测试

#spring:
#  security:
#    user:
#      name: dascom
#      password: dascom