spring:
  application:
    name: eureka-server
---
spring:
  profiles: dev

server:
  port: 8761 #启动端口

eureka:
  instance:
    hostname: 127.0.0.1 #eureka服务端的实例名称
  client:
    register-with-eureka: false      #false表示不向注册中心注册自己。
    fetch-registry: false           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    enable-self-preservation: false   #Eureka服务端关闭心跳连接测试
    eviction-interval-timer-in-ms: 4000
---
spring:
  profiles: dev-peer1

server:
  port: 8761 #启动端口

eureka:
  instance:
    hostname: eureka1 #eureka服务端的实例名称
  client:
    register-with-eureka: true      #false表示不向注册中心注册自己。
    fetch-registry: true           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka2:8762/eureka/
  server:
    enable-self-preservation: false   #Eureka服务端关闭心跳连接测试
    eviction-interval-timer-in-ms: 4000
---
spring:
  profiles: dev-peer2

server:
  port: 8762 #启动端口

eureka:
  instance:
    hostname: eureka2 #eureka服务端的实例名称 TODO eureka2、eureka1需要在C:\Windows\System32\drivers\etc hosts文件中配置
  client:
    register-with-eureka: true      #false表示不向注册中心注册自己。TODO 集群的时候设置成true
    fetch-registry: true           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka1:8761/eureka/ # TODO 把当前注册中心实例注册到其他注册中心节点上，多个用逗号隔开
  server:
    enable-self-preservation: false   #Eureka服务端关闭心跳连接测试
    eviction-interval-timer-in-ms: 4000
---
spring:
  profiles: test

server:
  port: 8761 #启动端口

eureka:
  instance:
    hostname: adev.top #eureka服务端的实例名称
  client:
    register-with-eureka: false      #false表示不向注册中心注册自己。
    fetch-registry: false           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://adev.top:8761/eureka/
  server:
    enable-self-preservation: false   #Eureka服务端关闭心跳连接测试
    eviction-interval-timer-in-ms: 4000